---
title: "p8105_hw5_xl2834"
author: "Xiaoyu Li"
date: "11/10/2020"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(ggridges)
library(p8105.datasets)

knitr::opts_chunk$set(
  fig.width = 8,
  fig.asp = .6,
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(1)
```

## Problem 1

```{r}
file_path = 
  list.files(path = "./data/hw5_data/data", full.names = TRUE)



read_data = function(x) {
  
  study_df = read_csv(x) %>% 
             mutate(arm_id = str_sub(x, start = -10, end = -5))
  
  study_df
}

output = vector("list", length = 10)

for (i in 1:10) {
  output[[i]] = read_data(file_path[[i]])
}

```


use map

```{r}
output = map(file_path, read_data)

study_result = 
  bind_rows(output) %>% 
  separate(arm_id, into = c("arm","id"), sep = "_") %>% 
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "observation") %>% 
  mutate(week = str_sub(week, -1))
```

```{r}
study_result %>% 
  ggplot(aes(x = week, y = observation, group = id, color = arm)) + 
  geom_line() +
  facet_grid(. ~ arm)
```

# Problem 2

```{r}
sim_mean_p = function(n = 30, mu = 0, sigma = 5) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data %>% 
    summarize(
      mu_hat = mean(x),
      p_value = broom::tidy(t.test(x, mu = 0))$p.value
    )
}


sim_results = 
  rerun(50, sim_mean_p(30, 0, 5)) %>% 
  bind_rows()
```

Repeat for mu = 1 to 6

```{r}
mu_list = 
  list(
    "mu_1"  = 1, 
    "mu_2"  = 2, 
    "mu_3" = 3, 
    "mu_4" = 4,
    "mu_5" = 5,
    "mu_6" = 6
    )

output = vector("list", length = 6)

for (i in 1:6) {
  output[[i]] = rerun(50, sim_mean_p(mu = mu_list[[i]])) %>% 
    bind_rows
}
```

Build a dataset

```{r}
result_df =
  tibble(
  mu = c(1, 2, 3, 4, 5, 6)
) %>% 
  mutate(
    output_lists = map(.x = mu, ~ rerun(50, sim_mean_p(mu = .x))),
    estimate_df = map(output_lists, bind_rows)
  ) %>% 
  select(-output_lists) %>% 
  unnest(estimate_df)
```


Make a plot showing the proportion of times the null was rejected (the power of the test) on the y axis and the true value of μ on the x axis. Describe the association between effect size and power.

```{r}

```



```{r}
sim = tibble(
    x = rnorm(n = 30, mean = 0, sd = 5),
  )

sim %>% 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
broom::tidy(t.test(rnorm(n = 30, mean = 0, sd = 5), mu = 0))$p.value

```

